version: "2.40.3"
services:
  web-app:
    # build . is needed otherwise Docker is not building your code.
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app          # <-- LIVE CODE SYNC
      - /home/app/node_modules   # <-- avoid overwriting node_modules
    command: npx nodemon --legacy-watch index.js  # <-- auto-reload server on changes
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=supersecret
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecret

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb